### ISSUE TITLE
Ping owner / the inviting user on join

### ISSUE THREAD

**Issue by ConnysCode** [xp-bot/v8#101]
When XP joins a server, it should ping either the inviting user or the owner if audit logs are disabled.

> Suggested by: 481099018676600853
> Thread: 1151434356947173407

**Comment by angelsflyinhell** [comment]
i think it should only ping the inviting member. if that info cannot be fetched, the ping should be left out.
e.g. on servers of twitch streamers, there's no good reason to ping the streamer, who's most likely the owner, but doesn't really care about the server or the bots on it
