### ISSUE TITLE
Centralize xp management

### ISSUE THREAD

**Issue by ConnysCode** [xp-bot/v8#97]
There has to be only one central function that manages xp logic and everything connected to it.

I've made this Experience in xp6 and 7 - this logic needs to be central and cannot be duplicated between many functions and handlers. It'll only cause issues in the longterm and will lead to unpredictable behaviour.

**Comment by angelsflyinhell** [comment]
We're currently using a centralized function for xp management in the `xp-db-connector` library. Which kind of benefits would a function that calls the lib function from the `xp-bot` project have?

ref: https://github.com/xp-bot/v8/blob/dev/xp-db-connector/src/guild_member.rs

**Comment by ConnysCode** [comment]
A centralized xp management function*.

A function that gets called from every event handler of interest, xp command, ... - that manages everything xp and level related from assigning roles over setting nicknames to actually setting xp.

Otherwise logic is duplicated multiple times for multiple types of xp and multiple commands and will have to get updated together all the time. This'll lead to inconsistent behaviour.

**Comment by ConnysCode** [comment]
@angelsflyinhell Has this been implemented?

Levelup messages do not seem to work when playing games.

**Comment by angelsflyinhell** [comment]
Has not been implemented as level up messages get handled seperately anyways so implementing this for games won't be too much of a hassle
